return {
  credits = { starting = 5000, capacity = 10000, tick = 30 },
  power = { deficitMultiplier = 0.5 },
  ore = { value = 25, gemMultiplier = 2, fieldRadius = 64 },
  build = { mcvDeployCommand = 34567, constructionRadius = 900 },
  factions = {
    allies = { name="Allies", countries={"America","France","Germany","Great Britain","Korea"} },
    soviet = { name="Soviet Union", countries={"Cuba","Iraq","Libya","Russia"} },
    yuri = { name="Yuri", countries={"Yuri"} },
  },
  countryBonuses = {
    America={paratrooper=true}, France={grandCannon=true}, Germany={tankDestroyer=true},
    GreatBritain={sniper=true}, Korea={blackEagle=true},
    Cuba={terrorist=true}, Iraq={desolator=true}, Libya={demolitionTruck=true}, Russia={teslaTank=true},
    Yuri={psychic=true},
  },
  units = {
    {id="gi",side="allies",production="barracks",cost=100},
    {id="conscript",side="soviet",production="barracks",cost=100},
    {id="initiates",side="yuri",production="barracks",cost=100},
    {id="grizzly_tank",side="allies",production="warfactory",cost=700},
    {id="rhino_tank",side="soviet",production="warfactory",cost=900},
    {id="lasher_tank",side="yuri",production="warfactory",cost=700},
    {id="allied_harvester",side="allies",production="warfactory",cost=1400},
    {id="soviet_harvester",side="soviet",production="warfactory",cost=1400},
    {id="yuri_slave_miner",side="yuri",production="warfactory",cost=1400},
  },
  buildings = {
    {id="allied_conyard",side="allies",requires={}},
    {id="allied_power",side="allies",requires={"allied_conyard"}},
    {id="allied_refinery",side="allies",requires={"allied_conyard","allied_power"}},
    {id="allied_barracks",side="allies",requires={"allied_conyard","allied_power"}},
    {id="allied_warfactory",side="allies",requires={"allied_conyard","allied_power","allied_refinery"}},
    {id="soviet_conyard",side="soviet",requires={}},
    {id="soviet_power",side="soviet",requires={"soviet_conyard"}},
    {id="soviet_refinery",side="soviet",requires={"soviet_conyard","soviet_power"}},
    {id="soviet_barracks",side="soviet",requires={"soviet_conyard","soviet_power"}},
    {id="soviet_warfactory",side="soviet",requires={"soviet_conyard","soviet_power","soviet_refinery"}},
    {id="yuri_conyard",side="yuri",requires={}},
    {id="yuri_power",side="yuri",requires={"yuri_conyard"}},
    {id="yuri_refinery",side="yuri",requires={"yuri_conyard","yuri_power"}},
    {id="yuri_barracks",side="yuri",requires={"yuri_conyard","yuri_power"}},
    {id="yuri_warfactory",side="yuri",requires={"yuri_conyard","yuri_power","yuri_refinery"}},
  },
  superweapons = {
    "chronosphere","iron_curtain","weather_control","nuclear_missile",
    "psychic_dominator","genetic_mutator","force_shield",
  },
}
